sudo: required

services:
  - docker

language: python

python:
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - python test/test.py

branches:
  only:
    - staging