language: python

python:
  - "3.6"
  #- "nightly"

os:
  - linux

addons:
  apt:
    packages:
      - wget

before_install:
  - bash scripts/geckodriver/download.sh travis

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - python test/test.py

branches:
  only:
    - staging